### ISSUE TITLE
Lukuvinkin otsikko yritetään selvittää URLin perusteella

### ISSUE THREAD

**Issue by pontushed** [tkt-sankarikoodaajat-2020/sankaristoorit#17]
Otetaan URLin perusteella sivun otsikko lukuvinkin otsikoksi. Jos lukuvinkillä on kirjoitettu otsikko, ei ylikirjoiteta.

**Comment by JohannesLares** [comment]
Omien koodien:
Oletus: 6h
Kului: 5h

**Comment by meklu** [comment]
Silottelu:
Oletus: 3h
Kului: 4h
